version: '3'
services:
  # redis:
  #   image: dtr.estl.moe/estl/redis:5
  #   restart: 'always'
  #   volumes:
  #     - redis:/data

  psql:
    image: dtr.estl.moe/estl/postgres:12
    restart: 'always'
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  # redis: {}
  psql: {}
